"""
Django settings for CryptoWebServer project.

Generated by 'django-admin startproject' using Django 1.11.29.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import dotenv

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'oll2s#^&o6g3xdo^sve73%1wvc_r#ms&_h4=06ygp!3nmhq4u1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

dotenv_file = os.path.join(BASE_DIR, ".env")
if os.path.isfile(dotenv_file):
    dotenv.load_dotenv(dotenv_file)

BINANCE_API_KEY =  os.environ['BINANCE_API_KEY']
BINANCE_API_SECRET =  os.environ['BINANCE_API_SECRET']

# Zerodha Configuration
ZERODHA_API_KEY = os.environ.get('ZERODHA_API_KEY', '')
ZERODHA_API_SECRET = os.environ.get('ZERODHA_API_SECRET', '')
ZERODHA_ACCESS_TOKEN = os.environ.get('ZERODHA_ACCESS_TOKEN', '')

# Redis Configuration
REDIS_HOST = os.environ.get('REDIS_HOST', 'localhost')
REDIS_PORT = os.environ.get('REDIS_PORT', '6379')
REDIS_DB = os.environ.get('REDIS_DB', '0')

# Kafka Configuration (for real-time price updates from CryptoMarketData)
KAFKA_BOOTSTRAP_SERVERS = os.environ.get('KAFKA_BOOTSTRAP_SERVERS', 'kafka:9092')
ENABLE_KAFKA_CONSUMER = os.environ.get('ENABLE_KAFKA_CONSUMER', 'True').lower() == 'true'

APP_NAME =  os.environ['APP_NAME']

# Microservices Configuration
# WEB_SERVER = os.environ['WEB_SERVER']
# MARKET_DATA = os.environ['MARKET_DATA']
# SENTIMENT_ENGINE = os.environ['SENTIMENT_ENGINE']

# CryptoTAEngine Configuration
TA_ENGINE_HOST = os.environ.get('TA_ENGINE_HOST', 'http://127.0.0.1')
TA_ENGINE_PORT = os.environ.get('TA_ENGINE_PORT', '8001')
TA_ENGINE = f"{TA_ENGINE_HOST}:{TA_ENGINE_PORT}"

# Sentiment Engine Configuration
SENTIMENT_ENGINE_URL = os.environ.get('SENTIMENT_ENGINE_URL', os.environ.get('SENTIMENT_ENGINE', None))

# TimescaleDB Configuration (shared with CryptoMarketData)
TIMESCALE_HOST = os.environ.get('TIMESCALE_HOST', 'localhost')
TIMESCALE_PORT = os.environ.get('TIMESCALE_PORT', '5432')
TIMESCALE_DB = os.environ.get('TIMESCALE_DB', 'market_data')
TIMESCALE_USER = os.environ.get('TIMESCALE_USER', 'postgres')
TIMESCALE_PASSWORD = os.environ.get('TIMESCALE_PASSWORD', 'postgres')

ALLOWED_HOSTS = [os.environ['ALLOWED_HOSTS'],'localhost','192.168.0.201']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'rest_framework',
    'home',
    'frontend.apps.FrontendConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files with Daphne/ASGI
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CryptoWebServer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CryptoWebServer.wsgi.application'
ASGI_APPLICATION = 'CryptoWebServer.asgi.application'

# Channel Layers Configuration (for WebSocket support)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(REDIS_HOST, int(REDIS_PORT))],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
# Using TimescaleDB (PostgreSQL) for all Django models

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': TIMESCALE_DB,
        'USER': TIMESCALE_USER,
        'PASSWORD': TIMESCALE_PASSWORD,
        'HOST': TIMESCALE_HOST,
        'PORT': TIMESCALE_PORT,
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise configuration for serving static files with Daphne/ASGI
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True if DEBUG else False


# Cache Configuration
# Redis cache for market data (symbols, OHLCV)
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
            'RETRY_ON_TIMEOUT': True,
            'MAX_CONNECTIONS': 50,
        },
        'KEY_PREFIX': 'vritti',
        'TIMEOUT': 300,  # Default TTL: 5 minutes
    }
}
