# Generated by Django 6.0 on 2025-12-16 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('strategy', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=20)),
                ('exchange', models.CharField(default='binance', max_length=20)),
                ('timeframe', models.CharField(max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('initial_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('parameters', models.TextField(default='{}')),
                ('status', models.CharField(default='submitted', max_length=20)),
                ('total_return', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_trades', models.IntegerField(blank=True, null=True)),
                ('win_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='home_backte_user_id_fcc16c_idx'), models.Index(fields=['status', '-created_at'], name='home_backte_status_c2d180_idx'), models.Index(fields=['symbol', '-created_at'], name='home_backte_symbol_17a927_idx')],
            },
        ),
    ]
